//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adens.DevToys.InitializationTool
{
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InitializationTool
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InitializationTool()
        {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adens.DevToys.InitializationTool.InitializationTool", typeof(InitializationTool).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 A InitializationTool extension for DevToys 的本地化字符串。
        /// </summary>
        internal static string AccessibleName
        {
            get
            {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Split file 的本地化字符串。
        /// </summary>
        internal static string Description
        {
            get
            {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 An unexpected error has occurred. 的本地化字符串。
        /// </summary>
        internal static string ErrorInfoDescription
        {
            get
            {
                return ResourceManager.GetString("ErrorInfoDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string ErrorInfoTitle
        {
            get
            {
                return ResourceManager.GetString("ErrorInfoTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 InitializationTool 的本地化字符串。
        /// </summary>
        internal static string LongDisplayTitle
        {
            get
            {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Output path 的本地化字符串。
        /// </summary>
        internal static string OutputFilePath
        {
            get
            {
                return ResourceManager.GetString("OutputFilePath", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Select save path 的本地化字符串。
        /// </summary>
        internal static string PickAFolder
        {
            get
            {
                return ResourceManager.GetString("PickAFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 InitializationTool 的本地化字符串。
        /// </summary>
        internal static string ShortDisplayTitle
        {
            get
            {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Split 的本地化字符串。
        /// </summary>
        internal static string Split
        {
            get
            {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Split size (KB) : 的本地化字符串。
        /// </summary>
        internal static string SplitSize
        {
            get
            {
                return ResourceManager.GetString("SplitSize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 File has been split successfully. 的本地化字符串。
        /// </summary>
        internal static string SplittedDescrtion
        {
            get
            {
                return ResourceManager.GetString("SplittedDescrtion", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string SplittedTitle
        {
            get
            {
                return ResourceManager.GetString("SplittedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Line 的本地化字符串。
        /// </summary>
        internal static string SplitType_Line
        {
            get
            {
                return ResourceManager.GetString("SplitType_Line", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string SplitType_Size
        {
            get
            {
                return ResourceManager.GetString("SplitType_Size", resourceCulture);
            }
        }
    }
}
