//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adens.DevToys.RsaGenerator {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RsaGenerator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RsaGenerator() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adens.DevToys.RsaGenerator.RsaGenerator", typeof(RsaGenerator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Rsa Generator 的本地化字符串。
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This will take a lot of time to generate {0} length .
        ///Benchmark:
        ///
        ///```
        ///
        ///BenchmarkDotNet v0.14.0, Windows 11 (10.0.22631.4317/23H2/2023Update/SunValley3)
        ///Intel Core i7-10700 CPU 2.90GHz, 1 CPU, 16 logical and 8 physical cores
        ///.NET SDK 8.0.403
        ///  [Host]     : .NET 8.0.10 (8.0.1024.46610), X64 RyuJIT AVX2
        ///  DefaultJob : .NET 8.0.10 (8.0.1024.46610), X64 RyuJIT AVX2
        ///
        ///
        ///```
        ///
        ///2048   |     48.72 ms 
        ///4096   |    445.01 ms 
        ///6144   |  1,547.98 ms
        ///8192   |  4,467.49 ms
        ///10240  |  8,943.09 ms 
        ///12288  | 1 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Rsa keypair generator extension for DevToys 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bits should be 384  &lt;= bits &lt;= 16384 and be a multiple of 8 的本地化字符串。
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 的本地化字符串。
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating... 的本地化字符串。
        /// </summary>
        internal static string Generating {
            get {
                return ResourceManager.GetString("Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key length 的本地化字符串。
        /// </summary>
        internal static string Keylength {
            get {
                return ResourceManager.GetString("Keylength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rsa Generator 的本地化字符串。
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Private key 的本地化字符串。
        /// </summary>
        internal static string Privatekey {
            get {
                return ResourceManager.GetString("Privatekey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Public key 的本地化字符串。
        /// </summary>
        internal static string Publickey {
            get {
                return ResourceManager.GetString("Publickey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rsa Generator 的本地化字符串。
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
    }
}
