name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Pack
      run: dotnet pack --no-build --configuration Release
      # This command assumes your project is set up to create a NuGet package during build

    - name: Publish NuGet Package
      uses: nuget/publish-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        package: ./src/**/*.nupkg
        nuget-version: 4.0.x  # Replace with the version of the NuGet client you want to use

